name: Main branch workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Check App Build
    runs-on: ubuntu-latest
    steps:
      - name: Flutter App build
        if: github.event_name != 'push'
        run: ci/build.sh dev