name: Main branch workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Check App Build
    runs-on: ubuntu-latest
    steps:
      - name: Analyzing App Code
        run: flutter analyze
      - name: Flutter App build
        run: ci/build.sh dev
      - name: Running Tests
        run: flutter test