name: Main branch workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
      - name: Analyzing App Code
        run: flutter analyze --no-fatal-infos
      - name: Flutter App build
        run: flutter build web
      - name: Running Tests
        run: flutter test
