name: Main branch workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    - uses: actions/checkout@v2
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
        channel: 'stable'
    name: Check App Build
    runs-on: ubuntu-latest
    steps:
      - name: Analyzing App Code
        run: flutter analyze
      - name: Flutter App build
        run: flutter build web
      - name: Running Tests
        run: flutter test
